- name: check the facts
  hosts: local
  connection: local
  tasks:
  - name: install nginx if os is redhat
    ansible.builtin.dnf:
      name: nginx
      status: latest
    when: ansible_os_family == "RedHat"

  - name: install nginx if os is Debian
    ansible.builtin.apt:
      name: nginx
      status: latest
    when: ansible_os_family == "Debian"
